version: "3.8"

services:
  frontend:
    build:
      context: ./azure-salesforce-app
      dockerfile: Dockerfile
    image: azure-salesforce-app:3
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./azure-salesforce-app/.env

  backend:
    build:
      context: ./azure-salesforce-server
      dockerfile: Dockerfile
    image: azure-salesforce-server
    ports:
      - "8000:8000"
    env_file:
      - ./azure-salesforce-server/.env
